apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-exporter
  namespace: exporter
  labels:
    app: postgres-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-exporter
  template:
    metadata:
      name: postres-exporter
      labels:
        app: postgres-exporter
    spec:
      containers:
        - name: postgres-exporter
        #hay una issue del checkpoints_timed en los logs
          image: bitnami/postgres-exporter
          env:
            - name: DATA_SOURCE_NAME
              value: "postgresql://dbuser:dbpassword@postgres-service.db.svc.cluster.local:5432/app_db_prod?sslmode=disable"
          ports:
            - name: pe1
              containerPort: 9187
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-exporter
  namespace: exporter
spec:
  ports:
    - name: pe
      port: 9187
      targetPort: 9187
  selector:
    app: postgres-exporter