apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-exporter
  labels:
    app: redis-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-exporter
  template:
    metadata:
      labels:
        app: redis-exporter
    spec:
      containers:
        - name: redis-exporter
          image: oliver006/redis_exporter:latest
          ports:
            - name: re1
              containerPort: 9121
          env:
            - name: REDIS_ADDR
              value: "redis://redis-service:6379"  # Reemplaza <host> con el nombre de tu servicio de Redis
---
apiVersion: v1
kind: Service
metadata:
  name: redis-exporter
spec:
  ports:
    - name: re
      port: 9121
      targetPort: 9121
  selector:
    app: redis-exporter
