apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
  labels:
    name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    rule_files:
      - /etc/prometheus/alerts_rules.yml

    scrape_configs:

      - job_name: 'app'
        static_configs:
          - targets: ['app-service.app.svc.cluster.local:80']

      - job_name: 'postgres-exporter'
        static_configs:
          - targets: ['postgres-exporter.exporter.svc.cluster.local:9187']

      - job_name: 'redis-exporter'
        static_configs:
          - targets: ['redis-exporter.exporter.svc.cluster.local:9121']

  alerts_rules.yml: |
    groups:
      - name: example-alerts
        rules:
          - alert: AppServiceDown
            expr: up{job="app"} == 0
            for: 1m
            labels:
              severity: critical
            annotations:
              summary: "El servicio de la aplicación no está disponible ({{ $labels.instance }})"
              description: "El servicio de la aplicación en {{ $labels.instance }} no ha respondido en los últimos 60 segundos."

          - alert: PostgresExporterDown
            expr: up{job="postgres-exporter"} == 0
            for: 1m
            labels:
              severity: critical
            annotations:
              summary: "PostgreSQL Exporter no está enviando métricas ({{ $labels.instance }})"
              description: "Postgres Exporter en {{ $labels.instance }} no ha enviado métricas en los últimos 60 segundos."