apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: app-monitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: app-service
  namespaceSelector:
    matchNames:
      - default
  endpoints:
  - port: app-p
    path: /metrics
    interval: 30s
