apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring
spec:
  selector:
    app: grafana
  ports:
    - protocol: TCP
      port: 80   # El puerto por el cual se accede desde fuera del clúster (LoadBalancer)
      targetPort: 3000  # El puerto interno del pod donde Grafana está escuchando
  type: NodePort  # Cambia esto a LoadBalancer si usas un proveedor de nube o si prefieres exponerlo con un IP externa
