apiVersion: v1
kind: Service
metadata:
  name: loki
  labels:
    app: loki
spec:
  ports:
    - port: 3100
      targetPort: 3100
  selector:
    app: loki
  type: NodePort # Cambiar a LoadBalancer si usas un entorno cloud
