apiVersion: v1
kind: Pod
metadata:
  name: promtail
spec:
  containers:
  - name: promtail
    image: grafana/promtail:2.8.2
    volumeMounts:
    - name: logs
      mountPath: /var/log/containers
      readOnly: true
  volumes:
  - name: logs
    hostPath:
      path: /var/log/containers
